<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('AUTH_CHALLENGE_LIST', object)"
        ),
        new Get(security: "is_granted('AUTH_CHALLENGE_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_auth_challenge')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'challengeType' => 'partial',
    'secretHash' => 'partial',
    'expiresAt' => 'exact',
    'usedAt' => 'exact',
    'attemptCount' => 'exact',
    'lastAttemptAt' => 'exact',
    'ipAddress' => 'partial',
    'userAgent' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'challengeType',
    'secretHash',
    'expiresAt',
    'usedAt',
    'attemptCount',
    'lastAttemptAt',
    'ipAddress',
    'userAgent',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'user',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'challengeType' => 'partial',
    'secretHash' => 'partial',
    'expiresAt' => 'exact',
    'usedAt' => 'exact',
    'attemptCount' => 'exact',
    'lastAttemptAt' => 'exact',
    'ipAddress' => 'partial',
    'userAgent' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class AuthChallenge
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'auth_challenge_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'challenge_type', type: 'string', length: 50, nullable: false)]
    #[Groups(['read'])]
    private string $challengeType;

    #[ORM\Column(name: 'secret_hash', type: 'string', length: 128, nullable: false)]
    #[Groups(['read'])]
    private string $secretHash;

    #[ORM\Column(name: 'expires_at', type: 'datetimetz_immutable', nullable: false)]
    #[Groups(['read'])]
    private DateTimeImmutable $expiresAt;

    #[ORM\Column(name: 'used_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $usedAt = null;

    #[ORM\Column(name: 'attempt_count', type: 'integer', nullable: false)]
    #[Groups(['read'])]
    private int $attemptCount;

    #[ORM\Column(name: 'last_attempt_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastAttemptAt = null;

    #[ORM\Column(name: 'ip_address', type: 'string', nullable: true)]
    #[Groups(['read'])]
    private ?string $ipAddress = null;

    #[ORM\Column(name: 'user_agent', type: 'text', nullable: true)]
    #[Groups(['read'])]
    private ?string $userAgent = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['auth_challenge_user'])]
    private ?User $user = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getChallengeType(): string
    {
        return $this->challengeType;
    }

    public function setChallengeType(string $challengeType): void
    {
        $this->challengeType = $challengeType;
    }

    public function getSecretHash(): string
    {
        return $this->secretHash;
    }

    public function setSecretHash(string $secretHash): void
    {
        $this->secretHash = $secretHash;
    }

    public function getExpiresAt(): DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(DateTimeImmutable $expiresAt): void
    {
        $this->expiresAt = $expiresAt;
    }

    public function getUsedAt(): ?DateTimeImmutable
    {
        return $this->usedAt;
    }

    public function setUsedAt(?DateTimeImmutable $usedAt): void
    {
        $this->usedAt = $usedAt;
    }

    public function getAttemptCount(): int
    {
        return $this->attemptCount;
    }

    public function setAttemptCount(int $attemptCount): void
    {
        $this->attemptCount = $attemptCount;
    }

    public function getLastAttemptAt(): ?DateTimeImmutable
    {
        return $this->lastAttemptAt;
    }

    public function setLastAttemptAt(?DateTimeImmutable $lastAttemptAt): void
    {
        $this->lastAttemptAt = $lastAttemptAt;
    }

    public function getIpAddress(): ?string
    {
        return $this->ipAddress;
    }

    public function setIpAddress(?string $ipAddress): void
    {
        $this->ipAddress = $ipAddress;
    }

    public function getUserAgent(): ?string
    {
        return $this->userAgent;
    }

    public function setUserAgent(?string $userAgent): void
    {
        $this->userAgent = $userAgent;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    #[Groups(['read'])]
    public function getUserId(): ?string
    {
        return $this->getUser()?->getId();
    }
}
