<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\DataProvider\CountryCurrencyUserProvider;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('COUNTRY_CURRENCY_LIST', object)"
        ),
        new GetCollection(
            uriTemplate: '/country-currencies/user',
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('ROLE_USER') & is_granted('COUNTRY_CURRENCY_LIST', object)",
            provider: CountryCurrencyUserProvider::class
        ),
        new Get(security: "is_granted('COUNTRY_CURRENCY_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_country_currency')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'isPrimary' => 'exact',
    'countryCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'isPrimary',
    'countryCode',
    'currencyCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'isPrimary' => 'exact',
    'countryCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class CountryCurrency
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'country_currency_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'is_primary', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isPrimary;

    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: 'country_code', referencedColumnName: 'country_code', nullable: false)]
    #[Groups(['country_currency_country'])]
    private ?Country $country = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'currency_code', referencedColumnName: 'currency_code', nullable: false)]
    #[Groups(['country_currency_currency'])]
    private ?Currency $currency = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getIsPrimary(): bool
    {
        return $this->isPrimary;
    }

    public function setIsPrimary(bool $isPrimary): void
    {
        $this->isPrimary = $isPrimary;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): void
    {
        $this->country = $country;
    }

    #[Groups(['read'])]
    public function getCountryCode(): ?string
    {
        return $this->getCountry()?->getCode();
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): void
    {
        $this->currency = $currency;
    }

    #[Groups(['read'])]
    public function getCurrencyCode(): ?string
    {
        return $this->getCurrency()?->getCode();
    }
}
