<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('COUNTRY_LANGUAGE_HINT_LIST', object)"
        ),
        new Get(security: "is_granted('COUNTRY_LANGUAGE_HINT_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_country_language_hint')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'weight' => 'partial',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'weight',
    'countryCode',
    'languageCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'weight' => 'partial',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class CountryLanguageHint
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'country_language_hint_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'weight', type: 'string', nullable: false, options: ['default' => '100'])]
    #[Groups(['read'])]
    private string $weight;

    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: 'country_code', referencedColumnName: 'country_code', nullable: false)]
    #[Groups(['country_language_hint_country'])]
    private ?Country $country = null;

    #[ORM\ManyToOne(targetEntity: Language::class)]
    #[ORM\JoinColumn(name: 'language_code', referencedColumnName: 'language_code', nullable: false)]
    #[Groups(['country_language_hint_language'])]
    private ?Language $language = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getWeight(): string
    {
        return $this->weight;
    }

    public function setWeight(string $weight): void
    {
        $this->weight = $weight;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): void
    {
        $this->country = $country;
    }

    #[Groups(['read'])]
    public function getCountryCode(): ?string
    {
        return $this->getCountry()?->getCode();
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): void
    {
        $this->language = $language;
    }

    #[Groups(['read'])]
    public function getLanguageCode(): ?string
    {
        return $this->getLanguage()?->getCode();
    }
}
