<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('COUNTRY_LIST', object)"
        ),
        new Get(security: "is_granted('COUNTRY_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_country')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'nameEn' => 'partial',
    'nameNative' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
    'replacedByCountryCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'nameEn',
    'nameNative',
    'isActive',
    'isFeatured',
    'replacedByCountryCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'nameEn' => 'partial',
    'nameNative' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
    'replacedByCountryCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Country
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'country_code', type: 'string', length: 2, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'country_name_en', type: 'string', length: 150, nullable: false)]
    #[Groups(['read'])]
    private string $nameEn;

    #[ORM\Column(name: 'country_name_native', type: 'string', length: 150, nullable: true)]
    #[Groups(['read'])]
    private ?string $nameNative = null;

    #[ORM\Column(name: 'is_active', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isActive;

    #[ORM\Column(name: 'is_featured', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isFeatured;

    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: 'replaced_by_country_code', referencedColumnName: 'country_code', nullable: true)]
    #[Groups(['country_replaced_by_country'])]
    private ?Country $replacedByCountry = null;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getNameEn(): string
    {
        return $this->nameEn;
    }

    public function setNameEn(string $nameEn): void
    {
        $this->nameEn = $nameEn;
    }

    public function getNameNative(): ?string
    {
        return $this->nameNative;
    }

    public function setNameNative(?string $nameNative): void
    {
        $this->nameNative = $nameNative;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    public function getIsFeatured(): bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(bool $isFeatured): void
    {
        $this->isFeatured = $isFeatured;
    }

    public function getReplacedByCountry(): ?Country
    {
        return $this->replacedByCountry;
    }

    public function setReplacedByCountry(?Country $replacedByCountry): void
    {
        $this->replacedByCountry = $replacedByCountry;
    }

    #[Groups(['read'])]
    public function getReplacedByCountryCode(): ?string
    {
        return $this->getReplacedByCountry()?->getCode();
    }
}
