<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('CURRENCY_LIST', object)",
            order: ['isFeatured' => 'DESC', 'nameEn' => 'ASC']
        ),
        new Get(security: "is_granted('CURRENCY_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_currency')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'nameEn' => 'partial',
    'minorUnits' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'nameEn',
    'minorUnits',
    'isActive',
    'isFeatured',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'nameEn' => 'partial',
    'minorUnits' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Currency
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'currency_code', type: 'string', length: 3, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'currency_name_en', type: 'string', length: 100, nullable: false)]
    #[Groups(['read'])]
    private string $nameEn;

    #[ORM\Column(name: 'minor_units', type: 'string', nullable: false, options: ['default' => '2'])]
    #[Groups(['read'])]
    private string $minorUnits;

    #[ORM\Column(name: 'is_active', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isActive;

    #[ORM\Column(name: 'is_featured', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isFeatured;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getNameEn(): string
    {
        return $this->nameEn;
    }

    public function setNameEn(string $nameEn): void
    {
        $this->nameEn = $nameEn;
    }

    public function getMinorUnits(): string
    {
        return $this->minorUnits;
    }

    public function setMinorUnits(string $minorUnits): void
    {
        $this->minorUnits = $minorUnits;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    public function getIsFeatured(): bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(bool $isFeatured): void
    {
        $this->isFeatured = $isFeatured;
    }
}
