<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Patch;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Validator\Constraints as CustomAssert;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('DEVICE_TYPE_LIST', object)"
        ),
        new Get(security: "is_granted('DEVICE_TYPE_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('DEVICE_TYPE_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('DEVICE_TYPE_UPDATE', object)",
            validationContext: ['groups' => ['update']]
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.device_type')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'code' => 'partial',
    'label' => 'partial',
    'configSchemaJson' => 'exact',
    'configDefaultsJson' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'ownerUser' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'code',
    'label',
    'configSchemaJson',
    'configDefaultsJson',
    'createdAt',
    'updatedAt',
    'removedAt',
    'ownerUser',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'code' => 'partial',
    'label' => 'partial',
    'configSchemaJson' => 'exact',
    'configDefaultsJson' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'ownerUser' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['code'],
    conditions: ['ownerUserId' => null],
    groups: ['create', 'update']
)]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['ownerUser', 'label'],
    conditions: ['removedAt' => null],
    groups: ['create', 'update']
)]
class DeviceType
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'device_type_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'code', type: 'text', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $code = null;

    #[ORM\Column(name: 'label', type: 'text', nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $label;

    #[ORM\Column(name: 'config_schema_json', type: 'json', nullable: false, options: ['default' => '\'{}\'::jsonb'])]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private array $configSchemaJson;

    #[ORM\Column(name: 'config_defaults_json', type: 'json', nullable: false, options: ['default' => '\'{}\'::jsonb'])]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private array $configDefaultsJson;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $updatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'owner_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['device_type_owner_user', 'create', 'update'])]
    private ?User $ownerUser = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    public function getConfigSchemaJson(): array
    {
        return $this->configSchemaJson;
    }

    public function setConfigSchemaJson(array $configSchemaJson): void
    {
        $this->configSchemaJson = $configSchemaJson;
    }

    public function getConfigDefaultsJson(): array
    {
        return $this->configDefaultsJson;
    }

    public function setConfigDefaultsJson(array $configDefaultsJson): void
    {
        $this->configDefaultsJson = $configDefaultsJson;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getOwnerUser(): ?User
    {
        return $this->ownerUser;
    }

    public function setOwnerUser(?User $ownerUser): void
    {
        $this->ownerUser = $ownerUser;
    }

    #[Groups(['read'])]
    public function getOwnerUserId(): ?string
    {
        return $this->getOwnerUser()?->getId();
    }
}
