<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\DeviceOwnershipFilter;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Patch;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as CustomAssert;
use App\State\Device\DeviceCreateProcessor;
use App\State\Device\DeviceDeleteProcessor;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('DEVICE_LIST', object)"
        ),
        new Get(security: "is_granted('DEVICE_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            securityPostDenormalize: "is_granted('DEVICE_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class,
            processor: DeviceCreateProcessor::class
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('DEVICE_UPDATE', object)",
            validationContext: ['groups' => ['update']]
        ),
        new Delete(
            security: "is_granted('DEVICE_UPDATE', object)",
            processor: DeviceDeleteProcessor::class
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.device')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'visibility' => 'partial',
    'manufacturer' => 'partial',
    'model' => 'partial',
    'nameShort' => 'partial',
    'nameFull' => 'partial',
    'poles' => 'exact',
    'sizeMm' => 'exact',
    'defaultTerminalsJson' => 'exact',
    'configJson' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'ownerUser' => 'exact',
    'deviceType' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'visibility',
    'manufacturer',
    'model',
    'nameShort',
    'nameFull',
    'poles',
    'sizeMm',
    'defaultTerminalsJson',
    'configJson',
    'createdAt',
    'updatedAt',
    'removedAt',
    'ownerUser',
    'deviceType',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'visibility' => 'partial',
    'manufacturer' => 'partial',
    'model' => 'partial',
    'nameShort' => 'partial',
    'nameFull' => 'partial',
    'poles' => 'exact',
    'sizeMm' => 'exact',
    'defaultTerminalsJson' => 'exact',
    'configJson' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'ownerUser' => 'exact',
    'deviceType' => 'exact',
])]
#[ApiFilter(DeviceOwnershipFilter::class)]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['ownerUser', 'manufacturer', 'model'],
    conditions: ['removedAt' => null],
    groups: ['create', 'update']
)]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['manufacturer', 'model'],
    conditions: ['ownerUser' => null],
    groups: ['create', 'update']
)]
class Device
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'device_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'visibility', type: 'text', nullable: false, options: ['default' => '\'private\'::text'])]
    #[Groups(['read', 'create', 'update'])]
    private string $visibility;

    #[ORM\Column(name: 'manufacturer', type: 'text', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $manufacturer = null;

    #[ORM\Column(name: 'model', type: 'text', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $model = null;

    #[ORM\Column(name: 'name_short', type: 'text', nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $nameShort;

    #[ORM\Column(name: 'name_full', type: 'text', nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $nameFull;

    #[ORM\Column(name: 'poles', type: 'integer', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?int $poles = null;

    #[ORM\Column(name: 'size_mm', type: 'decimal', precision: 10, scale: 2, nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $sizeMm;

    #[ORM\Column(name: 'default_terminals_json', type: 'json', nullable: false, options: ['default' => '\'[]\'::jsonb'])]
    #[Groups(['read', 'create', 'update'])]
    private array $defaultTerminalsJson;

    #[ORM\Column(name: 'config_json', type: 'json', nullable: false, options: ['default' => '\'{}\'::jsonb'])]
    #[Groups(['read', 'create', 'update'])]
    private array $configJson;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $updatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'owner_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['device_owner_user'])]
    private ?User $ownerUser = null;

    #[ORM\ManyToOne(targetEntity: DeviceType::class)]
    #[ORM\JoinColumn(name: 'device_type_code', referencedColumnName: 'code', nullable: false)]
    #[Assert\NotBlank(groups: ['device_type'])]
    #[Groups(['device_type', 'create', 'update'])]
    private ?DeviceType $type = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getVisibility(): string
    {
        return $this->visibility;
    }

    public function setVisibility(string $visibility): void
    {
        $this->visibility = $visibility;
    }

    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    public function setManufacturer(?string $manufacturer): void
    {
        $this->manufacturer = $manufacturer;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): void
    {
        $this->model = $model;
    }

    public function getNameShort(): string
    {
        return $this->nameShort;
    }

    public function setNameShort(string $nameShort): void
    {
        $this->nameShort = $nameShort;
    }

    public function getNameFull(): string
    {
        return $this->nameFull;
    }

    public function setNameFull(string $nameFull): void
    {
        $this->nameFull = $nameFull;
    }

    public function getPoles(): ?int
    {
        return $this->poles;
    }

    public function setPoles(?int $poles): void
    {
        $this->poles = $poles;
    }

    public function getSizeMm(): string
    {
        return $this->sizeMm;
    }

    public function setSizeMm(string $sizeMm): void
    {
        $this->sizeMm = $sizeMm;
    }

    public function getDefaultTerminalsJson(): array
    {
        return $this->defaultTerminalsJson;
    }

    public function setDefaultTerminalsJson(array $defaultTerminalsJson): void
    {
        $this->defaultTerminalsJson = $defaultTerminalsJson;
    }

    public function getConfigJson(): array
    {
        return $this->configJson;
    }

    public function setConfigJson(array $configJson): void
    {
        $this->configJson = $configJson;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getOwnerUser(): ?User
    {
        return $this->ownerUser;
    }

    public function setOwnerUser(?User $ownerUser): void
    {
        $this->ownerUser = $ownerUser;
    }

    #[Groups(['read'])]
    public function getOwnerUserId(): ?string
    {
        return $this->getOwnerUser()?->getId();
    }

    public function getType(): ?DeviceType
    {
        return $this->type;
    }

    public function setType(?DeviceType $type): void
    {
        $this->type = $type;
    }

    #[Groups(['read'])]
    public function getTypeCode(): ?string
    {
        return $this->getType()?->getCode();
    }
}
