<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('FX_RATE_LIST', object)"
        ),
        new Get(security: "is_granted('FX_RATE_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_fx_rate')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'rate' => 'partial',
    'rateDate' => 'exact',
    'fetchedAt' => 'exact',
    'fromCurrencyCode' => 'exact',
    'toCurrencyCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'rate',
    'rateDate',
    'fetchedAt',
    'fromCurrencyCode',
    'toCurrencyCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'rate' => 'partial',
    'rateDate' => 'exact',
    'fetchedAt' => 'exact',
    'fromCurrencyCode' => 'exact',
    'toCurrencyCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class FxRate
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'fx_rate_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'rate', type: 'decimal', precision: 18, scale: 8, nullable: false)]
    #[Groups(['read'])]
    private string $rate;

    #[ORM\Column(name: 'rate_date', type: 'date_immutable', nullable: false)]
    #[Groups(['read'])]
    private DateTimeImmutable $rateDate;

    #[ORM\Column(name: 'fetched_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $fetchedAt;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'from_currency_code', referencedColumnName: 'currency_code', nullable: false)]
    #[Groups(['fx_rate_from_currency'])]
    private ?Currency $fromCurrency = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'to_currency_code', referencedColumnName: 'currency_code', nullable: false)]
    #[Groups(['fx_rate_to_currency'])]
    private ?Currency $toCurrency = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getRate(): string
    {
        return $this->rate;
    }

    public function setRate(string $rate): void
    {
        $this->rate = $rate;
    }

    public function getRateDate(): DateTimeImmutable
    {
        return $this->rateDate;
    }

    public function setRateDate(DateTimeImmutable $rateDate): void
    {
        $this->rateDate = $rateDate;
    }

    public function getFetchedAt(): DateTimeImmutable
    {
        return $this->fetchedAt;
    }

    public function setFetchedAt(DateTimeImmutable $fetchedAt): void
    {
        $this->fetchedAt = $fetchedAt;
    }

    public function getFromCurrency(): ?Currency
    {
        return $this->fromCurrency;
    }

    public function setFromCurrency(?Currency $fromCurrency): void
    {
        $this->fromCurrency = $fromCurrency;
    }

    #[Groups(['read'])]
    public function getFromCurrencyCode(): ?string
    {
        return $this->getFromCurrency()?->getCode();
    }

    public function getToCurrency(): ?Currency
    {
        return $this->toCurrency;
    }

    public function setToCurrency(?Currency $toCurrency): void
    {
        $this->toCurrency = $toCurrency;
    }

    #[Groups(['read'])]
    public function getToCurrencyCode(): ?string
    {
        return $this->getToCurrency()?->getCode();
    }
}
