<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Post;
use ApiPlatform\State\CreateProvider;
use App\State\GiftListItemReservation\GiftListItemReservationCreateProcessor;
use App\State\GiftListItemReservation\GiftListItemReservationDeleteProcessor;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Validator\Constraints as CustomAssert;

#[ApiResource(
    operations: [
        new GetCollection(
            uriTemplate: '/gift-list-items/{giftListItem}/reservations',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'reservations',
                    fromClass: GiftListItem::class
                )
            ],
            order: ['createdAt' => 'DESC'],
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_ITEM_RESERVATION_LIST', object)"
        ),
        new Get(
            uriTemplate: '/gift-list-items/{giftListItem}/reservations/{id}',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'reservations',
                    fromClass: GiftListItem::class
                ),
                'id' => new Link(fromClass: GiftListItemReservation::class)
            ],
            security: "is_granted('GIFT_LIST_ITEM_RESERVATION_SHOW', object)",
        ),
        new Post(
            uriTemplate: '/gift-list-items/{giftListItem}/reservations',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'reservations',
                    fromClass: GiftListItem::class
                )
            ],
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('GIFT_LIST_ITEM_RESERVATION_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class,
            processor: GiftListItemReservationCreateProcessor::class
        ),
        new Delete(
            uriTemplate: '/gift-list-items/{giftListItem}/reservations/{id}',
            security: "is_granted('GIFT_LIST_ITEM_RESERVATION_DELETE', object)",
            processor: GiftListItemReservationDeleteProcessor::class
        ),
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_item_reservation')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'sharePercent' => 'exact',
    'shareAmount' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'reservedByUser' => 'exact',
    'statusCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'sharePercent',
    'shareAmount',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'giftListItem',
    'reservedByUser',
    'statusCode',
    'currencyCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'sharePercent' => 'exact',
    'shareAmount' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'reservedByUser' => 'exact',
    'statusCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['giftListItem', 'reservedByUser'],
    conditions: ['removedAt' => null],
    groups: ['create']
)]
class GiftListItemReservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_item_reservation_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'share_percent', type: 'integer', nullable: true)]
    #[Assert\Type(type: 'int', groups: ['read', 'create'])]
    #[Groups(['read', 'create'])]
    private ?int $sharePercent = null;

    #[ORM\Column(name: 'share_amount', type: 'decimal', precision: 12, scale: 2, nullable: true)]
    #[Groups(['read', 'create'])]
    private ?string $shareAmount = null;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    #[Groups(['read'])]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\Column(name: 'fx_rate_date', type: 'date_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $fxRateDate = null;

    #[ORM\Column(name: 'share_amount_in_gift_currency', type: 'decimal', precision: 22, scale: 2, nullable: true)]
    #[Groups(['read'])]
    private ?string $shareAmountInGiftCurrency = null;

    #[ORM\ManyToOne(targetEntity: GiftListItem::class)]
    #[ORM\JoinColumn(name: 'gift_list_item_id', referencedColumnName: 'gift_list_item_id', nullable: false)]
    #[Assert\NotBlank(groups: ['create'])]
    #[Groups(['gift_list_item_reservation_gift_list_item', 'create'])]
    private ?GiftListItem $giftListItem = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'reserved_by_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['gift_list_item_reservation_reserved_by_user'])]
    private ?User $reservedByUser = null;

    #[ORM\ManyToOne(targetEntity: GiftListItemReservationStatus::class)]
    #[ORM\JoinColumn(name: 'status_code', referencedColumnName: 'gift_list_item_reservation_status_code', nullable: false)]
    #[Groups(['gift_list_item_reservation_status'])]
    private ?GiftListItemReservationStatus $status = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'currency_code', referencedColumnName: 'currency_code', nullable: true)]
    #[Groups(['gift_list_item_reservation_currency', 'create'])]
    private ?Currency $currency = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'gift_currency_snapshot_code', referencedColumnName: 'currency_code', nullable: true)]
    #[Groups(['gift_list_item_reservation_gift_currency_snapshot'])]
    private ?Currency $giftCurrencySnapshot = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getSharePercent(): ?int
    {
        return $this->sharePercent;
    }

    public function setSharePercent(?int $sharePercent): void
    {
        $this->sharePercent = $sharePercent;
    }

    public function getShareAmount(): ?string
    {
        return $this->shareAmount;
    }

    public function setShareAmount(?string $shareAmount): void
    {
        $this->shareAmount = $shareAmount;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getFxRateDate(): ?DateTimeImmutable
    {
        return $this->fxRateDate;
    }

    public function setFxRateDate(?DateTimeImmutable $fxRateDate): void
    {
        $this->fxRateDate = $fxRateDate;
    }

    public function getShareAmountInGiftCurrency(): ?string
    {
        return $this->shareAmountInGiftCurrency;
    }

    public function setShareAmountInGiftCurrency(?string $shareAmountInGiftCurrency): void
    {
        $this->shareAmountInGiftCurrency = $shareAmountInGiftCurrency;
    }

    public function getGiftListItem(): ?GiftListItem
    {
        return $this->giftListItem;
    }

    public function setGiftListItem(?GiftListItem $giftListItem): void
    {
        $this->giftListItem = $giftListItem;
    }

    #[Groups(['read'])]
    public function getGiftListItemId(): ?string
    {
        return $this->getGiftListItem()?->getId();
    }

    public function getReservedByUser(): ?User
    {
        return $this->reservedByUser;
    }

    public function setReservedByUser(?User $reservedByUser): void
    {
        $this->reservedByUser = $reservedByUser;
    }

    #[Groups(['read'])]
    public function getReservedByUserId(): ?string
    {
        return $this->getReservedByUser()?->getId();
    }

    public function getStatus(): ?GiftListItemReservationStatus
    {
        return $this->status;
    }

    public function setStatus(?GiftListItemReservationStatus $status): void
    {
        $this->status = $status;
    }

    #[Groups(['read'])]
    public function getStatusCode(): ?string
    {
        return $this->getStatus()?->getCode();
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): void
    {
        $this->currency = $currency;
    }

    #[Groups(['read'])]
    public function getCurrencyCode(): ?string
    {
        return $this->getCurrency()?->getCode();
    }

    public function getGiftCurrencySnapshot(): ?Currency
    {
        return $this->giftCurrencySnapshot;
    }

    public function setGiftCurrencySnapshot(?Currency $giftCurrencySnapshot): void
    {
        $this->giftCurrencySnapshot = $giftCurrencySnapshot;
    }

    #[Groups(['read'])]
    public function getGiftCurrencySnapshotCode(): ?string
    {
        return $this->getGiftCurrencySnapshot()?->getCode();
    }
}
