<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Post;
use ApiPlatform\State\CreateProvider;
use App\DTO\LinkPreview;
use App\State\GiftListItemLink\GiftListItemLinkCreateProcessor;
use App\State\GiftListItemLink\GiftListItemLinkDeleteProcessor;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    operations: [
        new GetCollection(
            uriTemplate: '/gift-list-items/{giftListItem}/links',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'links',
                    fromClass: GiftListItem::class
                )
            ],
            order: ['createdAt' => 'DESC'],
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_ITEM_LINK_LIST', object)",
        ),
        new Get(security: "is_granted('GIFT_LIST_ITEM_LINK_SHOW', object)"),
        new Post(
            uriTemplate: '/gift-list-items/{giftListItem}/links',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'links',
                    fromClass: GiftListItem::class
                )
            ],
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('GIFT_LIST_ITEM_LINK_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class,
            processor: GiftListItemLinkCreateProcessor::class
        ),
        new Delete(
            uriTemplate: '/gift-list-items/{giftListItem}/links/{id}',
            security: "is_granted('GIFT_LIST_ITEM_LINK_DELETE', object)",
            processor: GiftListItemLinkDeleteProcessor::class
        ),
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_item_link')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'linkType' => 'partial',
    'providerCode' => 'partial',
    'url' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'createdByUser' => 'exact',
    'linkHost' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'linkType',
    'providerCode',
    'url',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'giftListItem',
    'createdByUser',
    'linkHost',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'linkType' => 'partial',
    'providerCode' => 'partial',
    'url' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'createdByUser' => 'exact',
    'linkHost' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class GiftListItemLink
{
    public const LINK_TYPE_WEB = 'WEB';
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_item_link_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'link_type', type: 'string', length: 30, nullable: false)]
    #[Groups(['read'])]
    private string $linkType;

    #[ORM\Column(name: 'provider_code', type: 'string', length: 50, nullable: true)]
    #[Groups(['read'])]
    private ?string $providerCode = null;


    #[ORM\Column(name: 'url', type: 'string', length: 800, nullable: false)]
    #[Groups(['read', 'create'])]
    #[Assert\NotBlank(message: 'URL must not be empty.', groups: ['create'])]
    #[Assert\Url(
        message: 'Please provide a valid URL.',
        protocols: ['http', 'https'],
        groups: ['create'],
        requireTld: true
    )]
    private string $url;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\Column(name: 'preview_json', type: 'link_preview_dto', nullable: true)]
    #[Groups(['gift_list_item_link_preview_json'])]
    private ?LinkPreview $previewJson = null;

    #[ORM\Column(name: 'preview_status', type: 'string', length: 30, nullable: true)]
    private ?string $previewStatus = null;

    #[ORM\Column(name: 'preview_fetched_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $previewFetchedAt = null;

    #[ORM\Column(name: 'preview_expires_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $previewExpiresAt = null;

    #[ORM\Column(name: 'gift_list_item_link_domain', type: 'string', length: 255, nullable: false)]
    #[Groups(['read'])]
    private string $domain;

    #[ORM\Column(name: 'gift_list_item_link_description', type: 'string', length: 255, nullable: true)]
    #[Groups(['read', 'create'])]
    private ?string $description = null;

    #[ORM\Column(name: 'preview_processing_locked_until', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $previewProcessingLockedUntil = null;

    #[ORM\Column(name: 'preview_processing_lock_token', type: 'uuid', nullable: true)]
    #[Groups(['read'])]
    private ?string $previewProcessingLockToken = null;

    #[ORM\ManyToOne(targetEntity: GiftListItem::class)]
    #[ORM\JoinColumn(name: 'gift_list_item_id', referencedColumnName: 'gift_list_item_id', nullable: false)]
    #[Groups(['gift_list_item_link_gift_list_item'])]
    private ?GiftListItem $giftListItem = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['gift_list_item_link_created_by_user'])]
    private ?User $createdByUser = null;

    #[ORM\ManyToOne(targetEntity: LinkHost::class)]
    #[ORM\JoinColumn(name: 'link_host_id', referencedColumnName: 'link_host_id', nullable: true)]
    #[Groups(['gift_list_item_link_link_host'])]
    private ?LinkHost $linkHost = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getLinkType(): string
    {
        return $this->linkType;
    }

    public function setLinkType(string $linkType): void
    {
        $this->linkType = $linkType;
    }

    public function getProviderCode(): ?string
    {
        return $this->providerCode;
    }

    public function setProviderCode(?string $providerCode): void
    {
        $this->providerCode = $providerCode;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getPreviewJson(): ?LinkPreview
    {
        return $this->previewJson;
    }

    public function setPreviewJson(?LinkPreview $previewJson): void
    {
        $this->previewJson = $previewJson;
    }

    public function getPreviewStatus(): ?string
    {
        return $this->previewStatus;
    }

    public function setPreviewStatus(?string $previewStatus): void
    {
        $this->previewStatus = $previewStatus;
    }

    public function getPreviewFetchedAt(): ?DateTimeImmutable
    {
        return $this->previewFetchedAt;
    }

    public function setPreviewFetchedAt(?DateTimeImmutable $previewFetchedAt): void
    {
        $this->previewFetchedAt = $previewFetchedAt;
    }

    public function getPreviewExpiresAt(): ?DateTimeImmutable
    {
        return $this->previewExpiresAt;
    }

    public function setPreviewExpiresAt(?DateTimeImmutable $previewExpiresAt): void
    {
        $this->previewExpiresAt = $previewExpiresAt;
    }

    public function getDomain(): string
    {
        return $this->domain;
    }

    public function setDomain(string $domain): void
    {
        $this->domain = $domain;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    public function getPreviewProcessingLockedUntil(): ?DateTimeImmutable
    {
        return $this->previewProcessingLockedUntil;
    }

    public function setPreviewProcessingLockedUntil(?DateTimeImmutable $previewProcessingLockedUntil): void
    {
        $this->previewProcessingLockedUntil = $previewProcessingLockedUntil;
    }

    public function getPreviewProcessingLockToken(): ?string
    {
        return $this->previewProcessingLockToken;
    }

    public function setPreviewProcessingLockToken(?string $previewProcessingLockToken): void
    {
        $this->previewProcessingLockToken = $previewProcessingLockToken;
    }

    public function getGiftListItem(): ?GiftListItem
    {
        return $this->giftListItem;
    }

    public function setGiftListItem(?GiftListItem $giftListItem): void
    {
        $this->giftListItem = $giftListItem;
    }

    #[Groups(['read'])]
    public function getGiftListItemId(): ?string
    {
        return $this->getGiftListItem()?->getId();
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): void
    {
        $this->createdByUser = $createdByUser;
    }

    #[Groups(['read'])]
    public function getCreatedByUserId(): ?string
    {
        return $this->getCreatedByUser()?->getId();
    }

    public function getLinkHost(): ?LinkHost
    {
        return $this->linkHost;
    }

    public function setLinkHost(?LinkHost $linkHost): void
    {
        $this->linkHost = $linkHost;
    }

    #[Groups(['read'])]
    public function getLinkHostId(): ?string
    {
        return $this->getLinkHost()?->getId();
    }
}
