<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Serializer\Filter\GroupFilter;
use ApiPlatform\State\CreateProvider;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use App\DataProvider\GiftListDefaultProvider;
use App\State\GiftList\GiftListCreateProcessor;
use App\Validator\Constraints as CustomAssert;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_LIST', object)"
        ),
        new Get(
            uriTemplate: '/gift-lists/default',
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('IS_AUTHENTICATED_FULLY')",
            provider: GiftListDefaultProvider::class
        ),
        new Get(security: "is_granted('GIFT_LIST_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            securityPostDenormalize: "is_granted('GIFT_LIST_CREATE', object)",
            validationContext: ['groups' => ['create']],
            processor: GiftListCreateProcessor::class,
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('GIFT_LIST_UPDATE', object)",
            validationContext: ['groups' => ['update']]
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'displayName' => 'partial',
    'shareSlug' => 'partial',
    'isUnlisted' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListTypeCode' => 'exact',
    'createdByUser' => 'exact',
    'ownerUser' => 'exact',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
    'currencyCode' => 'exact',
    'ownerPerson' => 'exact',
    'event' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'displayName',
    'shareSlug',
    'isUnlisted',
    'metadata',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'giftListTypeCode',
    'createdByUser',
    'ownerUser',
    'countryCode',
    'languageCode',
    'currencyCode',
    'ownerPerson',
    'event',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'displayName' => 'partial',
    'shareSlug' => 'partial',
    'isUnlisted' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListTypeCode' => 'exact',
    'createdByUser' => 'exact',
    'ownerUser' => 'exact',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
    'currencyCode' => 'exact',
    'ownerPerson' => 'exact',
    'event' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['shareSlug'],
    conditions: ['removedAt' => null],
    groups: ['create', 'update']
)]
class GiftList
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'display_name', type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Assert\Length(max: 255, groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $displayName;

    #[ORM\Column(name: 'share_slug', type: 'string', length: 80, nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'update'])]
    #[Assert\Length(max: 80, groups: ['read', 'update'])]
    #[Groups(['read'])]
    private string $shareSlug;

    #[ORM\Column(name: 'is_unlisted', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Assert\NotNull(groups: ['update'])]
    #[Groups(['read', 'create', 'update'])]
    private bool $isUnlisted;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Assert\NotBlank(groups: ['update'])]
    #[Groups(['read', 'create', 'update'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: GiftListType::class)]
    #[ORM\JoinColumn(name: 'gift_list_type_code', referencedColumnName: 'gift_list_type_code', nullable: true)]
    #[Groups(['gift_list_type', 'create', 'update'])]
    private ?GiftListType $type = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Assert\NotBlank(groups: ['update'])]
    #[Groups(['gift_list_created_by_user', 'create', 'update'])]
    private ?User $createdByUser = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'owner_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['gift_list_owner_user', 'create', 'update'])]
    private ?User $ownerUser = null;

    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: 'country_code', referencedColumnName: 'country_code', nullable: true)]
    #[Groups(['gift_list_country', 'create', 'update'])]
    private ?Country $country = null;

    #[ORM\ManyToOne(targetEntity: Language::class)]
    #[ORM\JoinColumn(name: 'language_code', referencedColumnName: 'language_code', nullable: true)]
    #[Groups(['gift_list_language', 'create', 'update'])]
    private ?Language $language = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'currency_code', referencedColumnName: 'currency_code', nullable: true)]
    #[Groups(['gift_list_currency', 'create', 'update'])]
    private ?Currency $currency = null;

    #[ORM\ManyToOne(targetEntity: Person::class)]
    #[ORM\JoinColumn(name: 'owner_person_id', referencedColumnName: 'person_id', nullable: true)]
    #[Groups(['gift_list_owner_person', 'create'])]
    private ?Person $ownerPerson = null;

    #[ORM\ManyToOne(targetEntity: Event::class)]
    #[ORM\JoinColumn(name: 'event_id', referencedColumnName: 'event_id', nullable: true)]
    #[Groups(['gift_list_event', 'create'])]
    private ?Event $event = null;

    #[ORM\OneToMany(targetEntity: GiftListItem::class, mappedBy: 'giftList', fetch: 'EXTRA_LAZY')]
    #[Groups(['gift_list_gift_list_items'])]
    private Collection | ArrayCollection $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getDisplayName(): string
    {
        return $this->displayName;
    }

    public function setDisplayName(string $displayName): void
    {
        $this->displayName = $displayName;
    }

    public function getShareSlug(): string
    {
        return $this->shareSlug;
    }

    public function setShareSlug(string $shareSlug): void
    {
        $this->shareSlug = $shareSlug;
    }

    public function getIsUnlisted(): bool
    {
        return $this->isUnlisted;
    }

    public function setIsUnlisted(bool $isUnlisted): void
    {
        $this->isUnlisted = $isUnlisted;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getType(): ?GiftListType
    {
        return $this->type;
    }

    public function setType(?GiftListType $type): void
    {
        $this->type = $type;
    }

    #[Groups(['read'])]
    public function getTypeCode(): ?string
    {
        return $this->getType()?->getCode();
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): void
    {
        $this->createdByUser = $createdByUser;
    }

    #[Groups(['read'])]
    public function getCreatedByUserId(): ?string
    {
        return $this->getCreatedByUser()?->getId();
    }

    public function getOwnerUser(): ?User
    {
        return $this->ownerUser;
    }

    public function setOwnerUser(?User $ownerUser): void
    {
        $this->ownerUser = $ownerUser;
    }

    #[Groups(['read'])]
    public function getOwnerUserId(): ?string
    {
        return $this->getOwnerUser()?->getId();
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): void
    {
        $this->country = $country;
    }

    #[Groups(['read'])]
    public function getCountryCode(): ?string
    {
        return $this->getCountry()?->getCode();
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): void
    {
        $this->language = $language;
    }

    #[Groups(['read'])]
    public function getLanguageCode(): ?string
    {
        return $this->getLanguage()?->getCode();
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): void
    {
        $this->currency = $currency;
    }

    #[Groups(['read'])]
    public function getCurrencyCode(): ?string
    {
        return $this->getCurrency()?->getCode();
    }

    public function getItems(): ArrayCollection|Collection
    {
        return $this->items;
    }

    public function setItems(ArrayCollection|Collection $items): void
    {
        $this->items = $items;
    }

    public function getOwnerPerson(): ?Person
    {
        return $this->ownerPerson;
    }

    public function setOwnerPerson(?Person $ownerPerson): void
    {
        $this->ownerPerson = $ownerPerson;
    }

    #[Groups(['read'])]
    public function getOwnerPersonId(): ?string
    {
        return $this->getOwnerPerson()?->getId();
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): void
    {
        $this->event = $event;
    }

    #[Groups(['read'])]
    public function getEventId(): ?string
    {
        return $this->getEvent()?->getId();
    }
}
