<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use App\State\GiftListItem\GiftListItemCreateProcessor;
use App\State\GiftListItem\GiftListItemDeleteProcessor;
use App\State\GiftListItem\GiftListItemUpdateProcessor;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Delete;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Validator\Constraints as CustomAssert;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_ITEM_LIST', object)"
        ),
        new Get(security: "is_granted('GIFT_LIST_ITEM_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('GIFT_LIST_ITEM_CREATE', object)",
            validationContext: ['groups' => ['create']],
            //            provider: CreateProvider::class,
            processor: GiftListItemCreateProcessor::class,
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('GIFT_LIST_ITEM_UPDATE', object)",
            validationContext: ['groups' => ['update']],
            processor: GiftListItemUpdateProcessor::class
        ),
        new Delete(
            security: "is_granted('GIFT_LIST_ITEM_DELETE', object)",
            processor: GiftListItemDeleteProcessor::class
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_item')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'shareSlug' => 'partial',
    'name' => 'partial',
    'description' => 'partial',
    'priceFrom' => 'partial',
    'priceTo' => 'partial',
    'expiresAt' => 'exact',
    'desire' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftList' => 'exact',
    'currencyCode' => 'exact',
    'statusCode' => 'exact',
    'createdByUser' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'shareSlug',
    'name',
    'description',
    'priceFrom',
    'priceTo',
    'expiresAt',
    'desire',
    'metadata',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'giftList',
    'currencyCode',
    'statusCode',
    'createdByUser',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'shareSlug' => 'partial',
    'name' => 'partial',
    'description' => 'partial',
    'priceFrom' => 'partial',
    'priceTo' => 'partial',
    'expiresAt' => 'exact',
    'desire' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftList' => 'exact',
    'currencyCode' => 'exact',
    'statusCode' => 'exact',
    'createdByUser' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['shareSlug'],
    conditions: ['removedAt' => null],
    groups: ['create', 'update']
)]
class GiftListItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_item_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'share_slug', type: 'string', length: 80, nullable: false)]
    #[Assert\NotBlank(groups: ['update'])]
    #[Assert\Length(max: 80, groups: ['update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $shareSlug;

    #[ORM\Column(name: 'gift_list_item_name', type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Assert\Length(max: 255, groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $name;

    #[ORM\Column(name: 'description', type: 'text', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $description = null;

    #[ORM\Column(name: 'price_from', type: 'decimal', precision: 12, scale: 2, nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $priceFrom = null;

    #[ORM\Column(name: 'price_to', type: 'decimal', precision: 12, scale: 2, nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?string $priceTo = null;

    #[ORM\Column(name: 'expires_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $expiresAt = null;

    #[ORM\Column(name: 'desire', type: 'integer', nullable: false, options: ['default' => '50'])]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Assert\Type(type: 'int', groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private int $desire;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Assert\NotBlank(groups: ['update'])]
    #[Groups(['read', 'create', 'update'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: GiftList::class)]
    #[ORM\JoinColumn(name: 'gift_list_id', referencedColumnName: 'gift_list_id', nullable: false)]
    #[Assert\NotBlank(groups: ['gift_list_item_gift_list', 'create', 'update'])]
    #[Groups(['gift_list_item_gift_list', 'create', 'update'])]
    private ?GiftList $giftList = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'currency_code', referencedColumnName: 'currency_code', nullable: true)]
    #[Groups(['gift_list_item_currency', 'create', 'update'])]
    private ?Currency $currency = null;

    #[ORM\ManyToOne(targetEntity: GiftListItemStatus::class)]
    #[ORM\JoinColumn(name: 'status_code', referencedColumnName: 'gift_list_item_status_code', nullable: false)]
    #[Assert\NotBlank(groups: ['update'])]
    #[Groups(['gift_list_item_status', 'create', 'update'])]
    private ?GiftListItemStatus $status = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Assert\NotBlank(groups: ['update'])]
    #[Groups(['gift_list_item_created_by_user', 'create', 'update'])]
    private ?User $createdByUser = null;

    #[ORM\OneToMany(targetEntity: GiftListItemComment::class, mappedBy: 'giftListItem', fetch: 'EXTRA_LAZY')]
    #[Groups(['gift_list_item_comments'])]
    private Collection | ArrayCollection $comments;

    #[ORM\OneToMany(targetEntity: GiftListItemReservation::class, mappedBy: 'giftListItem', fetch: 'EXTRA_LAZY')]
    #[Groups(['gift_list_item_reservations'])]
    private Collection | ArrayCollection $reservations;

    #[ORM\OneToMany(targetEntity: GiftListItemLink::class, mappedBy: 'giftListItem', fetch: 'EXTRA_LAZY')]
    #[Groups(['gift_list_item_links'])]
    private Collection | ArrayCollection $links;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->links = new ArrayCollection();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getShareSlug(): string
    {
        return $this->shareSlug;
    }

    public function setShareSlug(string $shareSlug): void
    {
        $this->shareSlug = $shareSlug;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    public function getPriceFrom(): ?string
    {
        return $this->priceFrom;
    }

    public function setPriceFrom(?string $priceFrom): void
    {
        $this->priceFrom = $priceFrom;
    }

    public function getPriceTo(): ?string
    {
        return $this->priceTo;
    }

    public function setPriceTo(?string $priceTo): void
    {
        $this->priceTo = $priceTo;
    }

    public function getExpiresAt(): ?DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(?DateTimeImmutable $expiresAt): void
    {
        $this->expiresAt = $expiresAt;
    }

    public function getDesire(): int
    {
        return $this->desire;
    }

    public function setDesire(int $desire): void
    {
        $this->desire = $desire;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getGiftList(): ?GiftList
    {
        return $this->giftList;
    }

    public function setGiftList(?GiftList $giftList): void
    {
        $this->giftList = $giftList;
    }

    #[Groups(['read'])]
    public function getGiftListId(): ?string
    {
        return $this->getGiftList()?->getId();
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): void
    {
        $this->currency = $currency;
    }

    #[Groups(['read'])]
    public function getCurrencyCode(): ?string
    {
        return $this->getCurrency()?->getCode();
    }

    public function getStatus(): ?GiftListItemStatus
    {
        return $this->status;
    }

    public function setStatus(?GiftListItemStatus $status): void
    {
        $this->status = $status;
    }

    #[Groups(['read'])]
    public function getStatusCode(): ?string
    {
        return $this->getStatus()?->getCode();
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): void
    {
        $this->createdByUser = $createdByUser;
    }

    #[Groups(['read'])]
    public function getCreatedByUserId(): ?string
    {
        return $this->getCreatedByUser()?->getId();
    }

    public function getComments(): ArrayCollection|Collection
    {
        return $this->comments;
    }

    public function setComments(ArrayCollection|Collection $comments): void
    {
        $this->comments = $comments;
    }

    public function getReservations(): ArrayCollection|Collection
    {
        return $this->reservations;
    }

    public function setReservations(ArrayCollection|Collection $reservations): void
    {
        $this->reservations = $reservations;
    }

    public function getLinks(): ArrayCollection|Collection
    {
        return $this->links;
    }

    public function setLinks(ArrayCollection|Collection $links): void
    {
        $this->links = $links;
    }
}
