<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_TYPE_LIST', object)"
        ),
        new Get(security: "is_granted('GIFT_LIST_TYPE_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_type')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isActive' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'name',
    'isActive',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isActive' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class GiftListType
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_type_code', type: 'string', length: 100, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'gift_list_type_name', type: 'string', length: 255, nullable: false)]
    #[Groups(['read'])]
    private string $name;

    #[ORM\Column(name: 'is_active', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isActive;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }
}
