<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use ApiPlatform\Metadata\Delete;
use App\State\GiftListItemComment\GiftListItemCommentCreateProcessor;
use App\State\GiftListItemComment\GiftListItemCommentDeleteProcessor;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    operations: [
        new GetCollection(
            uriTemplate: '/gift-list-items/{giftListItem}/comments',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'comments',
                    fromClass: GiftListItem::class
                )
            ],
            order: ['createdAt' => 'DESC'],
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_ITEM_COMMENT_LIST', object)"
        ),
        new Get(
            uriTemplate: '/gift-list-items/{giftListItem}/comments/{id}',
            security: "is_granted('GIFT_LIST_ITEM_COMMENT_SHOW', object)"
        ),
        new Post(
            uriTemplate: '/gift-list-items/{giftListItem}/comments',
            uriVariables: [
                'giftListItem' => new Link(
                    fromProperty: 'comments',
                    fromClass: GiftListItem::class
                )
            ],
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('GIFT_LIST_ITEM_COMMENT_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class,
            processor: GiftListItemCommentCreateProcessor::class
        ),
        new Delete(
            uriTemplate: '/gift-list-items/{giftListItem}/comments/{id}',
            security: "is_granted('GIFT_LIST_ITEM_COMMENT_DELETE', object)",
            processor: GiftListItemCommentDeleteProcessor::class
        ),
    //        new Patch(
    //            uriTemplate: '/gift-list-items/{giftListItem}/comments/{id}',
    //            normalizationContext: ['groups' => ['read']],
    //            denormalizationContext: ['groups' => ['update']],
    //            security: "is_granted('GIFT_LIST_ITEM_COMMENT_UPDATE', object)",
    //            validationContext: ['groups' => ['update']]
    //        )
    ],
    uriVariables: [
        'giftListItem' => new Link(
            fromProperty: 'comments',
            fromClass: GiftListItem::class
        ),
        'id' => new Link(fromClass: GiftListItemComment::class)
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_item_comment')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'commentText' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'createdByUser' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'commentText',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'giftListItem',
    'createdByUser',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'commentText' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'giftListItem' => 'exact',
    'createdByUser' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class GiftListItemComment
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_item_comment_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'comment_text', type: 'text', nullable: false)]
    #[Assert\NotBlank(groups: ['create', 'update'])]
    #[Groups(['read', 'create', 'update', 'admin'])]
    private string $text;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read', 'create', 'update'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read', 'create', 'update'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: GiftListItem::class)]
    #[ORM\JoinColumn(name: 'gift_list_item_id', referencedColumnName: 'gift_list_item_id', nullable: false)]
    #[Assert\NotBlank(groups: ['gift_list_item_comment_gift_list_item', 'create', 'update'])]
    #[Groups(['gift_list_item_comment_gift_list_item', 'create', 'update'])]
    private ?GiftListItem $giftListItem = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['gift_list_item_comment_created_by_user', 'create', 'update'])]
    private ?User $createdByUser = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): void
    {
        $this->text = $text;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getGiftListItem(): ?GiftListItem
    {
        return $this->giftListItem;
    }

    public function setGiftListItem(?GiftListItem $giftListItem): void
    {
        $this->giftListItem = $giftListItem;
    }

    #[Groups(['read'])]
    public function getGiftListItemId(): ?string
    {
        return $this->getGiftListItem()?->getId();
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): void
    {
        $this->createdByUser = $createdByUser;
    }

    #[Groups(['read'])]
    public function getCreatedByUserId(): ?string
    {
        return $this->getCreatedByUser()?->getId();
    }
}
