<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('GIFT_LIST_ITEM_RESERVATION_STATUS_LIST', object)"
        ),
        new Get(security: "is_granted('GIFT_LIST_ITEM_RESERVATION_STATUS_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_gift_list_item_reservation_status')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isFinal' => 'exact',
    'sortOrder' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'name',
    'isFinal',
    'sortOrder',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isFinal' => 'exact',
    'sortOrder' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class GiftListItemReservationStatus
{
    public const ACTIVE = 'ACTIVE';
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'gift_list_item_reservation_status_code', type: 'string', length: 50, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'gift_list_item_reservation_status_name', type: 'string', length: 100, nullable: false)]
    #[Groups(['read'])]
    private string $name;

    #[ORM\Column(name: 'is_final', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isFinal;

    #[ORM\Column(name: 'sort_order', type: 'integer', nullable: true)]
    #[Groups(['read'])]
    private ?int $sortOrder = null;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getIsFinal(): bool
    {
        return $this->isFinal;
    }

    public function setIsFinal(bool $isFinal): void
    {
        $this->isFinal = $isFinal;
    }

    public function getSortOrder(): ?int
    {
        return $this->sortOrder;
    }

    public function setSortOrder(?int $sortOrder): void
    {
        $this->sortOrder = $sortOrder;
    }
}
