<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('LANGUAGE_LIST', object)"
        ),
        new Get(security: "is_granted('LANGUAGE_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_language')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'baseCode' => 'partial',
    'nameEn' => 'partial',
    'nameNative' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'baseCode',
    'nameEn',
    'nameNative',
    'isActive',
    'isFeatured',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'baseCode' => 'partial',
    'nameEn' => 'partial',
    'nameNative' => 'partial',
    'isActive' => 'exact',
    'isFeatured' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Language
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'language_code', type: 'string', length: 35, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'language_base_code', type: 'string', length: 10, nullable: false)]
    #[Groups(['read'])]
    private string $baseCode;

    #[ORM\Column(name: 'language_name_en', type: 'string', length: 150, nullable: false)]
    #[Groups(['read'])]
    private string $nameEn;

    #[ORM\Column(name: 'language_name_native', type: 'string', length: 150, nullable: true)]
    #[Groups(['read'])]
    private ?string $nameNative = null;

    #[ORM\Column(name: 'is_active', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isActive;

    #[ORM\Column(name: 'is_featured', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isFeatured;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getBaseCode(): string
    {
        return $this->baseCode;
    }

    public function setBaseCode(string $baseCode): void
    {
        $this->baseCode = $baseCode;
    }

    public function getNameEn(): string
    {
        return $this->nameEn;
    }

    public function setNameEn(string $nameEn): void
    {
        $this->nameEn = $nameEn;
    }

    public function getNameNative(): ?string
    {
        return $this->nameNative;
    }

    public function setNameNative(?string $nameNative): void
    {
        $this->nameNative = $nameNative;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    public function getIsFeatured(): bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(bool $isFeatured): void
    {
        $this->isFeatured = $isFeatured;
    }
}
