<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('LINK_HOST_LIST', object)"
        ),
        new Get(security: "is_granted('LINK_HOST_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_link_host')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'host' => 'partial',
    'isPreviewEnabled' => 'exact',
    'faviconUrl' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'host',
    'isPreviewEnabled',
    'faviconUrl',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'host' => 'partial',
    'isPreviewEnabled' => 'exact',
    'faviconUrl' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class LinkHost
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'link_host_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'host', type: 'string', length: 255, nullable: false)]
    #[Groups(['read'])]
    private string $host;

    #[ORM\Column(name: 'is_preview_enabled', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isPreviewEnabled;

    #[ORM\Column(name: 'favicon_url', type: 'string', length: 800, nullable: true)]
    #[Groups(['read'])]
    private ?string $faviconUrl = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getHost(): string
    {
        return $this->host;
    }

    public function setHost(string $host): void
    {
        $this->host = $host;
    }

    public function getIsPreviewEnabled(): bool
    {
        return $this->isPreviewEnabled;
    }

    public function setIsPreviewEnabled(bool $isPreviewEnabled): void
    {
        $this->isPreviewEnabled = $isPreviewEnabled;
    }

    public function getFaviconUrl(): ?string
    {
        return $this->faviconUrl;
    }

    public function setFaviconUrl(?string $faviconUrl): void
    {
        $this->faviconUrl = $faviconUrl;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }
}
