<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('NOTIFICATION_LIST', object)"
        ),
        new Get(security: "is_granted('NOTIFICATION_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_notification')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'refNone' => 'exact',
    'payload' => 'exact',
    'isRead' => 'exact',
    'readAt' => 'exact',
    'isAcknowledged' => 'exact',
    'acknowledgedAt' => 'exact',
    'createdAt' => 'exact',
    'recipientUser' => 'exact',
    'user' => 'exact',
    'notificationTypeCode' => 'exact',
    'notificationCategoryCode' => 'exact',
    'refGiftList' => 'exact',
    'refGiftListItem' => 'exact',
    'refGiftListItemReservation' => 'exact',
    'refUser' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'refNone',
    'payload',
    'isRead',
    'readAt',
    'isAcknowledged',
    'acknowledgedAt',
    'createdAt',
    'recipientUser',
    'user',
    'notificationTypeCode',
    'notificationCategoryCode',
    'refGiftList',
    'refGiftListItem',
    'refGiftListItemReservation',
    'refUser',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'refNone' => 'exact',
    'payload' => 'exact',
    'isRead' => 'exact',
    'readAt' => 'exact',
    'isAcknowledged' => 'exact',
    'acknowledgedAt' => 'exact',
    'createdAt' => 'exact',
    'recipientUser' => 'exact',
    'user' => 'exact',
    'notificationTypeCode' => 'exact',
    'notificationCategoryCode' => 'exact',
    'refGiftList' => 'exact',
    'refGiftListItem' => 'exact',
    'refGiftListItemReservation' => 'exact',
    'refUser' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Notification
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'notification_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'ref_none', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $refNone;

    #[ORM\Column(name: 'payload', type: 'json', nullable: false, options: ['default' => '\'{}\'::jsonb'])]
    #[Groups(['read'])]
    private array $payload;

    #[ORM\Column(name: 'is_read', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isRead;

    #[ORM\Column(name: 'read_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $readAt = null;

    #[ORM\Column(name: 'is_acknowledged', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isAcknowledged;

    #[ORM\Column(name: 'acknowledged_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $acknowledgedAt = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'now()'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'recipient_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['notification_recipient_user'])]
    private ?User $recipientUser = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['notification_user'])]
    private ?User $user = null;

    #[ORM\ManyToOne(targetEntity: NotificationType::class)]
    #[ORM\JoinColumn(name: 'notification_type_code', referencedColumnName: 'notification_type_code', nullable: true)]
    #[Groups(['notification_type'])]
    private ?NotificationType $type = null;

    #[ORM\ManyToOne(targetEntity: NotificationCategory::class)]
    #[ORM\JoinColumn(name: 'notification_category_code', referencedColumnName: 'notification_category_code', nullable: true)]
    #[Groups(['notification_category'])]
    private ?NotificationCategory $category = null;

    #[ORM\ManyToOne(targetEntity: GiftList::class)]
    #[ORM\JoinColumn(name: 'ref_gift_list_id', referencedColumnName: 'gift_list_id', nullable: true)]
    #[Groups(['notification_ref_gift_list'])]
    private ?GiftList $refGiftList = null;

    #[ORM\ManyToOne(targetEntity: GiftListItem::class)]
    #[ORM\JoinColumn(name: 'ref_gift_list_item_id', referencedColumnName: 'gift_list_item_id', nullable: true)]
    #[Groups(['notification_ref_gift_list_item'])]
    private ?GiftListItem $refGiftListItem = null;

    #[ORM\ManyToOne(targetEntity: GiftListItemReservation::class)]
    #[ORM\JoinColumn(name: 'ref_gift_list_item_reservation_id', referencedColumnName: 'gift_list_item_reservation_id', nullable: true)]
    #[Groups(['notification_ref_gift_list_item_reservation'])]
    private ?GiftListItemReservation $refGiftListItemReservation = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'ref_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['notification_ref_user'])]
    private ?User $refUser = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getRefNone(): bool
    {
        return $this->refNone;
    }

    public function setRefNone(bool $refNone): void
    {
        $this->refNone = $refNone;
    }

    public function getPayload(): array
    {
        return $this->payload;
    }

    public function setPayload(array $payload): void
    {
        $this->payload = $payload;
    }

    public function getIsRead(): bool
    {
        return $this->isRead;
    }

    public function setIsRead(bool $isRead): void
    {
        $this->isRead = $isRead;
    }

    public function getReadAt(): ?DateTimeImmutable
    {
        return $this->readAt;
    }

    public function setReadAt(?DateTimeImmutable $readAt): void
    {
        $this->readAt = $readAt;
    }

    public function getIsAcknowledged(): bool
    {
        return $this->isAcknowledged;
    }

    public function setIsAcknowledged(bool $isAcknowledged): void
    {
        $this->isAcknowledged = $isAcknowledged;
    }

    public function getAcknowledgedAt(): ?DateTimeImmutable
    {
        return $this->acknowledgedAt;
    }

    public function setAcknowledgedAt(?DateTimeImmutable $acknowledgedAt): void
    {
        $this->acknowledgedAt = $acknowledgedAt;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getRecipientUser(): ?User
    {
        return $this->recipientUser;
    }

    public function setRecipientUser(?User $recipientUser): void
    {
        $this->recipientUser = $recipientUser;
    }

    #[Groups(['read'])]
    public function getRecipientUserId(): ?string
    {
        return $this->getRecipientUser()?->getId();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    #[Groups(['read'])]
    public function getUserId(): ?string
    {
        return $this->getUser()?->getId();
    }

    public function getType(): ?NotificationType
    {
        return $this->type;
    }

    public function setType(?NotificationType $type): void
    {
        $this->type = $type;
    }

    #[Groups(['read'])]
    public function getTypeCode(): ?string
    {
        return $this->getType()?->getCode();
    }

    public function getCategory(): ?NotificationCategory
    {
        return $this->category;
    }

    public function setCategory(?NotificationCategory $category): void
    {
        $this->category = $category;
    }

    #[Groups(['read'])]
    public function getCategoryCode(): ?string
    {
        return $this->getCategory()?->getCode();
    }

    public function getRefGiftList(): ?GiftList
    {
        return $this->refGiftList;
    }

    public function setRefGiftList(?GiftList $refGiftList): void
    {
        $this->refGiftList = $refGiftList;
    }

    #[Groups(['read'])]
    public function getRefGiftListId(): ?string
    {
        return $this->getRefGiftList()?->getId();
    }

    public function getRefGiftListItem(): ?GiftListItem
    {
        return $this->refGiftListItem;
    }

    public function setRefGiftListItem(?GiftListItem $refGiftListItem): void
    {
        $this->refGiftListItem = $refGiftListItem;
    }

    #[Groups(['read'])]
    public function getRefGiftListItemId(): ?string
    {
        return $this->getRefGiftListItem()?->getId();
    }

    public function getRefGiftListItemReservation(): ?GiftListItemReservation
    {
        return $this->refGiftListItemReservation;
    }

    public function setRefGiftListItemReservation(?GiftListItemReservation $refGiftListItemReservation): void
    {
        $this->refGiftListItemReservation = $refGiftListItemReservation;
    }

    #[Groups(['read'])]
    public function getRefGiftListItemReservationId(): ?string
    {
        return $this->getRefGiftListItemReservation()?->getId();
    }

    public function getRefUser(): ?User
    {
        return $this->refUser;
    }

    public function setRefUser(?User $refUser): void
    {
        $this->refUser = $refUser;
    }

    #[Groups(['read'])]
    public function getRefUserId(): ?string
    {
        return $this->getRefUser()?->getId();
    }
}
