<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('NOTIFICATION_CATEGORY_LIST', object)"
        ),
        new Get(security: "is_granted('NOTIFICATION_CATEGORY_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_notification_category')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isActive' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'name',
    'isActive',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'name' => 'partial',
    'isActive' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class NotificationCategory
{
    public const GIFT_LIST_ADMIN_ASSIGNED = 'GIFT_LIST_ADMIN_ASSIGNED';
    public const GIFT_LIST_ADMIN_REMOVED = 'GIFT_LIST_ADMIN_REMOVED';
    public const GIFT_LIST_CREATED = 'GIFT_LIST_CREATED';
    public const GIFT_LIST_ITEM_COMMENTED = 'GIFT_LIST_ITEM_COMMENTED';
    public const GIFT_LIST_ITEM_CREATED = 'GIFT_LIST_ITEM_CREATED';
    public const GIFT_LIST_ITEM_EXPIRED = 'GIFT_LIST_ITEM_EXPIRED';
    public const GIFT_LIST_ITEM_REMOVED = 'GIFT_LIST_ITEM_REMOVED';
    public const GIFT_LIST_ITEM_RESERVATION_REMOVED = 'GIFT_LIST_ITEM_RESERVATION_REMOVED';
    public const GIFT_LIST_ITEM_RESERVED = 'GIFT_LIST_ITEM_RESERVED';
    public const GIFT_LIST_ITEM_UPDATED = 'GIFT_LIST_ITEM_UPDATED';
    public const GIFT_LIST_REMOVED = 'GIFT_LIST_REMOVED';
    public const GIFT_LIST_SHARED = 'GIFT_LIST_SHARED';
    public const GIFT_LIST_UNSHARED = 'GIFT_LIST_UNSHARED';
    public const GIFT_LIST_UPDATED = 'GIFT_LIST_UPDATED';
    public const SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT';
    public const SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE';
    public const SYSTEM_SECURITY_ALERT = 'SYSTEM_SECURITY_ALERT';
    public const USER_CREATED = 'USER_CREATED';
    public const USER_DEACTIVATED = 'USER_DEACTIVATED';
    public const USER_REMOVED = 'USER_REMOVED';
    public const USER_VERIFIED = 'USER_VERIFIED';

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'notification_category_code', type: 'string', length: 100, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'notification_category_name', type: 'string', length: 255, nullable: false)]
    #[Groups(['read'])]
    private string $name;

    #[ORM\Column(name: 'is_active', type: 'boolean', nullable: false, options: ['default' => 'true'])]
    #[Groups(['read'])]
    private bool $isActive;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }
}
