<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use App\State\Person\PersonCreateProcessor;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Patch;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('PERSON_LIST', object)"
        ),
        new Get(security: "is_granted('PERSON_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            security: "is_granted('PERSON_CREATE', object)",
            validationContext: ['groups' => ['create']],
            processor: PersonCreateProcessor::class,
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('PERSON_UPDATE', object)",
            validationContext: ['groups' => ['update']]
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_person')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'displayName' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'createdByUser' => 'exact',
    'linkedUser' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'displayName',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'createdByUser',
    'linkedUser',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'displayName' => 'partial',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'createdByUser' => 'exact',
    'linkedUser' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Person
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'person_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'display_name', type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(groups: ['read', 'create', 'update'])]
    #[Assert\Length(max: 255, groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $displayName;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by_user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['person_created_by_user'])]
    private ?User $createdByUser = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'linked_user_id', referencedColumnName: 'user_id', nullable: true)]
    #[Groups(['person_linked_user'])]
    private ?User $linkedUser = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getDisplayName(): string
    {
        return $this->displayName;
    }

    public function setDisplayName(string $displayName): void
    {
        $this->displayName = $displayName;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): void
    {
        $this->createdByUser = $createdByUser;
    }

    #[Groups(['read'])]
    public function getCreatedByUserId(): ?string
    {
        return $this->getCreatedByUser()?->getId();
    }

    public function getLinkedUser(): ?User
    {
        return $this->linkedUser;
    }

    public function setLinkedUser(?User $linkedUser): void
    {
        $this->linkedUser = $linkedUser;
    }

    #[Groups(['read'])]
    public function getLinkedUserId(): ?string
    {
        return $this->getLinkedUser()?->getId();
    }
}
