<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('ROLE_LIST', object)"
        ),
        new Get(security: "is_granted('ROLE_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_role')]
#[ApiFilter(SearchFilter::class, properties: [
    'code' => 'exact',
    'scopeApi' => 'exact',
    'scopeUi' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'code',
    'scopeApi',
    'scopeUi',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'code' => 'exact',
    'scopeApi' => 'exact',
    'scopeUi' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class Role
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'role_code', type: 'string', length: 100, nullable: false)]
    #[Groups(['read'])]
    private string $code;

    #[ORM\Column(name: 'scope_api', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $scopeApi;

    #[ORM\Column(name: 'scope_ui', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $scopeUi;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getScopeApi(): bool
    {
        return $this->scopeApi;
    }

    public function setScopeApi(bool $scopeApi): void
    {
        $this->scopeApi = $scopeApi;
    }

    public function getScopeUi(): bool
    {
        return $this->scopeUi;
    }

    public function setScopeUi(bool $scopeUi): void
    {
        $this->scopeUi = $scopeUi;
    }
}
