<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use ApiPlatform\State\CreateProvider;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Patch;
use App\State\Switchboard\SwitchboardDeleteProcessor;
use App\State\Switchboard\SwitchboardCreateProcessor;
use App\State\Switchboard\SwitchboardUpdateProcessor;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Validator\Constraints as CustomAssert;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('SWITCHBOARD_LIST', object)"
        ),
        new Get(security: "is_granted('SWITCHBOARD_SHOW', object)"),
        new Post(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['create']],
            securityPostDenormalize: "is_granted('SWITCHBOARD_CREATE', object)",
            validationContext: ['groups' => ['create']],
            provider: CreateProvider::class,
            processor: SwitchboardCreateProcessor::class,
        ),
        new Patch(
            normalizationContext: ['groups' => ['read']],
            denormalizationContext: ['groups' => ['update']],
            security: "is_granted('SWITCHBOARD_UPDATE', object)",
            validationContext: ['groups' => ['update']],
            processor: SwitchboardUpdateProcessor::class
        ),
        new Delete(
            security: "is_granted('SWITCHBOARD_UPDATE', object)",
            processor: SwitchboardDeleteProcessor::class
        )
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_switchboard')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'name' => 'partial',
    'contentJson' => 'exact',
    'version' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'project' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'name',
    'contentJson',
    'version',
    'createdAt',
    'updatedAt',
    'removedAt',
    'project',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'name' => 'partial',
    'contentJson' => 'exact',
    'version' => 'exact',
    'createdAt' => 'exact',
    'updatedAt' => 'exact',
    'removedAt' => 'exact',
    'project' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
#[CustomAssert\EntityUniqueConstraint(
    fields: ['project', 'name'],
    conditions: ['removedAt' => null],
    groups: ['create', 'update']
)]
class Switchboard
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'switchboard_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'name', type: 'string', length: 255, nullable: false)]
    #[Assert\Length(max: 255, groups: ['read', 'create', 'update'])]
    #[Groups(['read', 'create', 'update'])]
    private string $name = '';

    #[ORM\Column(name: 'content_json', type: 'json', nullable: false, options: ['default' => '\'{}\'::jsonb'])]
    #[Groups(['read', 'create', 'update'])]
    private array $contentJson;

    #[ORM\Column(name: 'version', type: 'integer', nullable: false, options: ['default' => '1'])]
    #[Groups(['read'])]
    private int $version;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $updatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: Project::class)]
    #[ORM\JoinColumn(name: 'project_id', referencedColumnName: 'project_id', nullable: false)]
    #[Assert\NotBlank(groups: ['switchboard_project', 'create', 'update'])]
    #[Groups(['switchboard_project', 'create', 'update'])]
    private ?Project $project = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getContentJson(): array
    {
        return $this->contentJson;
    }

    public function setContentJson(array $contentJson): void
    {
        $this->contentJson = $contentJson;
    }

    public function getVersion(): int
    {
        return $this->version;
    }

    public function setVersion(int $version): void
    {
        $this->version = $version;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): void
    {
        $this->project = $project;
    }

    #[Groups(['read'])]
    public function getProjectId(): ?string
    {
        return $this->getProject()?->getId();
    }
}
