<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('USER_SESSION_LIST', object)"
        ),
        new Get(security: "is_granted('USER_SESSION_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_user_session')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'tokenHash' => 'partial',
    'deviceName' => 'partial',
    'deviceType' => 'partial',
    'userAgent' => 'partial',
    'ipAddress' => 'partial',
    'isTrusted' => 'exact',
    'lastUsedAt' => 'exact',
    'lastIpAddress' => 'partial',
    'expiresAt' => 'exact',
    'revokedAt' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'tokenHash',
    'deviceName',
    'deviceType',
    'userAgent',
    'ipAddress',
    'isTrusted',
    'lastUsedAt',
    'lastIpAddress',
    'expiresAt',
    'revokedAt',
    'metadata',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'user',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'tokenHash' => 'partial',
    'deviceName' => 'partial',
    'deviceType' => 'partial',
    'userAgent' => 'partial',
    'ipAddress' => 'partial',
    'isTrusted' => 'exact',
    'lastUsedAt' => 'exact',
    'lastIpAddress' => 'partial',
    'expiresAt' => 'exact',
    'revokedAt' => 'exact',
    'metadata' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class UserSession
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'user_session_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'token_hash', type: 'string', length: 128, nullable: false)]
    #[Groups(['read'])]
    private string $tokenHash;

    #[ORM\Column(name: 'device_name', type: 'string', length: 100, nullable: true)]
    #[Groups(['read'])]
    private ?string $deviceName = null;

    #[ORM\Column(name: 'device_type', type: 'string', length: 50, nullable: true)]
    #[Groups(['read'])]
    private ?string $deviceType = null;

    #[ORM\Column(name: 'user_agent', type: 'text', nullable: true)]
    #[Groups(['read'])]
    private ?string $userAgent = null;

    #[ORM\Column(name: 'ip_address', type: 'string', nullable: true)]
    #[Groups(['read'])]
    private ?string $ipAddress = null;

    #[ORM\Column(name: 'is_trusted', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isTrusted;

    #[ORM\Column(name: 'last_used_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUsedAt = null;

    #[ORM\Column(name: 'last_ip_address', type: 'string', nullable: true)]
    #[Groups(['read'])]
    private ?string $lastIpAddress = null;

    #[ORM\Column(name: 'expires_at', type: 'datetimetz_immutable', nullable: false)]
    #[Groups(['read'])]
    private DateTimeImmutable $expiresAt;

    #[ORM\Column(name: 'revoked_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $revokedAt = null;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    #[Groups(['read'])]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['user_session_user'])]
    private ?User $user = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getTokenHash(): string
    {
        return $this->tokenHash;
    }

    public function setTokenHash(string $tokenHash): void
    {
        $this->tokenHash = $tokenHash;
    }

    public function getDeviceName(): ?string
    {
        return $this->deviceName;
    }

    public function setDeviceName(?string $deviceName): void
    {
        $this->deviceName = $deviceName;
    }

    public function getDeviceType(): ?string
    {
        return $this->deviceType;
    }

    public function setDeviceType(?string $deviceType): void
    {
        $this->deviceType = $deviceType;
    }

    public function getUserAgent(): ?string
    {
        return $this->userAgent;
    }

    public function setUserAgent(?string $userAgent): void
    {
        $this->userAgent = $userAgent;
    }

    public function getIpAddress(): ?string
    {
        return $this->ipAddress;
    }

    public function setIpAddress(?string $ipAddress): void
    {
        $this->ipAddress = $ipAddress;
    }

    public function getIsTrusted(): bool
    {
        return $this->isTrusted;
    }

    public function setIsTrusted(bool $isTrusted): void
    {
        $this->isTrusted = $isTrusted;
    }

    public function getLastUsedAt(): ?DateTimeImmutable
    {
        return $this->lastUsedAt;
    }

    public function setLastUsedAt(?DateTimeImmutable $lastUsedAt): void
    {
        $this->lastUsedAt = $lastUsedAt;
    }

    public function getLastIpAddress(): ?string
    {
        return $this->lastIpAddress;
    }

    public function setLastIpAddress(?string $lastIpAddress): void
    {
        $this->lastIpAddress = $lastIpAddress;
    }

    public function getExpiresAt(): DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(DateTimeImmutable $expiresAt): void
    {
        $this->expiresAt = $expiresAt;
    }

    public function getRevokedAt(): ?DateTimeImmutable
    {
        return $this->revokedAt;
    }

    public function setRevokedAt(?DateTimeImmutable $revokedAt): void
    {
        $this->revokedAt = $revokedAt;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    #[Groups(['read'])]
    public function getUserId(): ?string
    {
        return $this->getUser()?->getId();
    }
}
