<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use DateTimeImmutable;
use Symfony\Component\Serializer\Attribute\SerializedName;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('USER_LIST', object)"
        ),
        new Get(security: "is_granted('USER_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_user')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'email' => 'partial',
    'firstName' => 'partial',
    'lastName' => 'partial',
    'alias' => 'partial',
    'avatarUrl' => 'partial',
    'isVerified' => 'exact',
    'emailVerifiedAt' => 'exact',
    'lastLoginAt' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'email',
    'firstName',
    'lastName',
    'alias',
    'avatarUrl',
    'isVerified',
    'emailVerifiedAt',
    'lastLoginAt',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'countryCode',
    'languageCode',
    'currencyCode',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'email' => 'partial',
    'firstName' => 'partial',
    'lastName' => 'partial',
    'alias' => 'partial',
    'avatarUrl' => 'partial',
    'isVerified' => 'exact',
    'emailVerifiedAt' => 'exact',
    'lastLoginAt' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'countryCode' => 'exact',
    'languageCode' => 'exact',
    'currencyCode' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    private array $apiRoles = [];
    /**
     * @var string[]
     */
    private array $uiRoles = [];

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'user_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'email', type: 'string', length: 180, nullable: true)]
    #[Groups(['read'])]
    private ?string $email = null;

    #[ORM\Column(name: 'password_hash', type: 'string', length: 255, nullable: true)]
    private ?string $passwordHash = null;

    #[ORM\Column(name: 'first_name', type: 'string', length: 100, nullable: true)]
    #[Groups(['read'])]
    private ?string $firstName = null;

    #[ORM\Column(name: 'last_name', type: 'string', length: 100, nullable: true)]
    #[Groups(['read'])]
    private ?string $lastName = null;

    #[ORM\Column(name: 'user_alias', type: 'string', length: 100, nullable: true)]
    #[Groups(['read'])]
    private ?string $alias = null;

    #[ORM\Column(name: 'avatar_url', type: 'string', length: 500, nullable: true)]
    #[Groups(['read'])]
    private ?string $avatarUrl = null;

    #[ORM\Column(name: 'is_verified', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $isVerified;

    #[ORM\Column(name: 'email_verified_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $emailVerifiedAt = null;

    #[ORM\Column(name: 'last_login_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $lastLoginAt = null;

    #[ORM\Column(name: 'metadata', type: 'json', nullable: true)]
    private ?array $metadata = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: 'country_code', referencedColumnName: 'country_code', nullable: true)]
    #[Groups(['user_country'])]
    private ?Country $country = null;

    #[ORM\ManyToOne(targetEntity: Language::class)]
    #[ORM\JoinColumn(name: 'language_code', referencedColumnName: 'language_code', nullable: true)]
    #[Groups(['user_language'])]
    private ?Language $language = null;

    #[ORM\ManyToOne(targetEntity: Currency::class)]
    #[ORM\JoinColumn(name: 'currency_code', referencedColumnName: 'currency_code', nullable: true)]
    #[Groups(['user_currency'])]
    private ?Currency $currency = null;

    #[ORM\OneToMany(targetEntity: UserGroup::class, mappedBy: 'group', fetch: 'EXTRA_LAZY')]
    #[Groups(['user_user_groups'])]
    private Collection | ArrayCollection $userGroups;

    public function __construct()
    {
        $this->userGroups = new ArrayCollection();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    public function getPasswordHash(): ?string
    {
        return $this->passwordHash;
    }

    public function setPasswordHash(?string $passwordHash): void
    {
        $this->passwordHash = $passwordHash;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(?string $alias): void
    {
        $this->alias = $alias;
    }

    public function getAvatarUrl(): ?string
    {
        return $this->avatarUrl;
    }

    public function setAvatarUrl(?string $avatarUrl): void
    {
        $this->avatarUrl = $avatarUrl;
    }

    public function getIsVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): void
    {
        $this->isVerified = $isVerified;
    }

    public function getEmailVerifiedAt(): ?DateTimeImmutable
    {
        return $this->emailVerifiedAt;
    }

    public function setEmailVerifiedAt(?DateTimeImmutable $emailVerifiedAt): void
    {
        $this->emailVerifiedAt = $emailVerifiedAt;
    }

    public function getLastLoginAt(): ?DateTimeImmutable
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(?DateTimeImmutable $lastLoginAt): void
    {
        $this->lastLoginAt = $lastLoginAt;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): void
    {
        $this->country = $country;
    }

    #[Groups(['read'])]
    public function getCountryCode(): ?string
    {
        return $this->getCountry()?->getCode();
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): void
    {
        $this->language = $language;
    }

    #[Groups(['read'])]
    public function getLanguageCode(): ?string
    {
        return $this->getLanguage()?->getCode();
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): void
    {
        $this->currency = $currency;
    }

    #[Groups(['read'])]
    public function getCurrencyCode(): ?string
    {
        return $this->getCurrency()?->getCode();
    }

    // UserInterface implementation
    public function getRoles(): array
    {
        return array_unique(array_merge($this->apiRoles, ['ROLE_USER']));
    }

    public function hasRole(string $role): bool
    {
        return in_array($role, $this->getRoles(), true);
    }

    /**
     * @return string[]
     */
    #[Groups(['read'])]
    #[SerializedName('roles')]
    public function getUIRoles(): array
    {
        return $this->uiRoles;
    }

    public function setLoadedRoles(array $apiRoles, array $uiRoles): void
    {
        $this->apiRoles = $apiRoles;
        $this->uiRoles = $uiRoles;
    }

    public function eraseCredentials(): void
    {
        // Nothing to erase - we don't store plain passwords
    }

    public function getUserIdentifier(): string
    {
        return $this->id;
    }

    // PasswordAuthenticatedUserInterface implementation
    public function getPassword(): ?string
    {
        return $this->passwordHash;
    }

    #[Groups(['read'])]
    public function getDisplayName(): string
    {
        $alias = trim(($this->getAlias() ?? ''));
        if ($alias) {
            return $alias;
        }

        $firstName = trim(($this->getFirstName() ?? ''));
        if ($firstName) {
            $lastName = trim(($this->getLastName() ?? ''));
            $lastInitial = $lastName ? (mb_substr($lastName, 0, 1) . '.') : null;

            return implode(' ', array_filter([$firstName, $lastInitial]));
        }

        $userId = $this->getId();
        $userIdSuffix = strtoupper(substr(str_replace('-', '', $userId), -8));

        return 'ID-' . $userIdSuffix;
    }

    public function getUserGroups(): ArrayCollection|Collection
    {
        return $this->userGroups;
    }

    public function setUserGroups(ArrayCollection|Collection $userGroups): void
    {
        $this->userGroups = $userGroups;
    }
}
