<?php

/**
* Resource generated by:
* bin/console app:make:resource
**/

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\ApiPlatform\Filter\MultiFieldSearchFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Serializer\Filter\GroupFilter;
use Symfony\Component\Serializer\Attribute\Groups;
use DateTimeImmutable;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['read']],
            security: "is_granted('USER_IDENTITY_LIST', object)"
        ),
        new Get(security: "is_granted('USER_IDENTITY_SHOW', object)")
    ],
    normalizationContext: ['groups' => ['read']],
)]
#[ORM\Entity]
#[ORM\Table(name: 'app.tbl_user_identity')]
#[ApiFilter(SearchFilter::class, properties: [
    'id' => 'exact',
    'provider' => 'partial',
    'providerSubject' => 'partial',
    'providerEmail' => 'partial',
    'providerEmailVerified' => 'exact',
    'lastUsedAt' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(OrderFilter::class, properties: [
    'id',
    'provider',
    'providerSubject',
    'providerEmail',
    'providerEmailVerified',
    'lastUsedAt',
    'createdAt',
    'lastUpdatedAt',
    'removedAt',
    'user',
])]
#[ApiFilter(MultiFieldSearchFilter::class, properties: [
    'id' => 'exact',
    'provider' => 'partial',
    'providerSubject' => 'partial',
    'providerEmail' => 'partial',
    'providerEmailVerified' => 'exact',
    'lastUsedAt' => 'exact',
    'createdAt' => 'exact',
    'lastUpdatedAt' => 'exact',
    'removedAt' => 'exact',
    'user' => 'exact',
])]
#[ApiFilter(GroupFilter::class, arguments: ['overrideDefaultGroups' => true])]
class UserIdentity
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'user_identity_id', type: 'uuid', nullable: false, options: ['default' => 'gen_random_uuid()'])]
    #[Groups(['read'])]
    private string $id;

    #[ORM\Column(name: 'provider', type: 'string', length: 50, nullable: false)]
    #[Groups(['read'])]
    private string $provider;

    #[ORM\Column(name: 'provider_subject', type: 'string', length: 255, nullable: false)]
    #[Groups(['read'])]
    private string $providerSubject;

    #[ORM\Column(name: 'provider_email', type: 'string', length: 180, nullable: true)]
    #[Groups(['read'])]
    private ?string $providerEmail = null;

    #[ORM\Column(name: 'provider_email_verified', type: 'boolean', nullable: false, options: ['default' => 'false'])]
    #[Groups(['read'])]
    private bool $providerEmailVerified;

    #[ORM\Column(name: 'last_used_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUsedAt = null;

    #[ORM\Column(name: 'created_at', type: 'datetimetz_immutable', nullable: false, options: ['default' => 'CURRENT_TIMESTAMP'])]
    #[Groups(['read'])]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'last_updated_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $lastUpdatedAt = null;

    #[ORM\Column(name: 'removed_at', type: 'datetimetz_immutable', nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeImmutable $removedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'user_id', nullable: false)]
    #[Groups(['user_identity_user'])]
    private ?User $user = null;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): void
    {
        $this->id = $id;
    }

    public function getProvider(): string
    {
        return $this->provider;
    }

    public function setProvider(string $provider): void
    {
        $this->provider = $provider;
    }

    public function getProviderSubject(): string
    {
        return $this->providerSubject;
    }

    public function setProviderSubject(string $providerSubject): void
    {
        $this->providerSubject = $providerSubject;
    }

    public function getProviderEmail(): ?string
    {
        return $this->providerEmail;
    }

    public function setProviderEmail(?string $providerEmail): void
    {
        $this->providerEmail = $providerEmail;
    }

    public function getProviderEmailVerified(): bool
    {
        return $this->providerEmailVerified;
    }

    public function setProviderEmailVerified(bool $providerEmailVerified): void
    {
        $this->providerEmailVerified = $providerEmailVerified;
    }

    public function getLastUsedAt(): ?DateTimeImmutable
    {
        return $this->lastUsedAt;
    }

    public function setLastUsedAt(?DateTimeImmutable $lastUsedAt): void
    {
        $this->lastUsedAt = $lastUsedAt;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getLastUpdatedAt(): ?DateTimeImmutable
    {
        return $this->lastUpdatedAt;
    }

    public function setLastUpdatedAt(?DateTimeImmutable $lastUpdatedAt): void
    {
        $this->lastUpdatedAt = $lastUpdatedAt;
    }

    public function getRemovedAt(): ?DateTimeImmutable
    {
        return $this->removedAt;
    }

    public function setRemovedAt(?DateTimeImmutable $removedAt): void
    {
        $this->removedAt = $removedAt;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    #[Groups(['read'])]
    public function getUserId(): ?string
    {
        return $this->getUser()?->getId();
    }
}
